# Import necessary dependencies and settings

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\Admin\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

# Sample corpus of text documents

In [2]:
corpus = ['The sky is blue and beautiful.',
          'Love this blue and beautiful sky!',
          'The quick brown fox jumps over the lazy dog.',
          'The brown fox is quick and the blue dog is lazy!',
          'The sky is very blue and the sky is very beautiful today',
          'The dog is lazy but the brown fox is quick!'    
]


Document Category
0                     The sky is blue and beautiful.  weather
1                  Love this blue and beautiful sky!  weather
2       The quick brown fox jumps over the lazy dog.  animals
3   The brown fox is quick and the blue dog is lazy!  animals
4  The sky is very blue and the sky is very beaut...  weather
5        The dog is lazy but the brown fox is quick!  animals

# Simple text pre-processing

Veamos qué hace np.vectorize().

Imaginemos una función que acepta un número y devuelve True o False si el número es o no par

In [5]:
# Probemos la función con un par de valores:



False

True

Esta función acepta un escalar, por lo que intentar usarla con un array NumPy devolverá un error. Pero podemos "vectorizarla" con la función np.vectorize

In [8]:
# Ahora ya es posible usarla con arrays


array([False,  True, False,  True, False])

Volvamos a procesamiento de Texto.

array(['The sky is blue and beautiful.',
       'Love this blue and beautiful sky!',
       'The quick brown fox jumps over the lazy dog.',
       'The brown fox is quick and the blue dog is lazy!',
       'The sky is very blue and the sky is very beautiful today',
       'The dog is lazy but the brown fox is quick!'], dtype='<U56')

['the', 'sky', 'is', 'blue', 'and', 'beautiful']
['sky', 'blue', 'beautiful']


'sky blue beautiful'

['the', 'sky', 'is', 'blue', 'and', 'beautiful']
['sky', 'blue', 'beautiful']
['the', 'sky', 'is', 'blue', 'and', 'beautiful']
['sky', 'blue', 'beautiful']
['love', 'this', 'blue', 'and', 'beautiful', 'sky']
['love', 'blue', 'beautiful', 'sky']
['the', 'quick', 'brown', 'fox', 'jumps', 'over', 'the', 'lazy', 'dog']
['quick', 'brown', 'fox', 'jumps', 'lazy', 'dog']
['the', 'brown', 'fox', 'is', 'quick', 'and', 'the', 'blue', 'dog', 'is', 'lazy']
['brown', 'fox', 'quick', 'blue', 'dog', 'lazy']
['the', 'sky', 'is', 'very', 'blue', 'and', 'the', 'sky', 'is', 'very', 'beautiful', 'today']
['sky', 'blue', 'sky', 'beautiful', 'today']
['the', 'dog', 'is', 'lazy', 'but', 'the', 'brown', 'fox', 'is', 'quick']
['dog', 'lazy', 'brown', 'fox', 'quick']


array(['sky blue beautiful', 'love blue beautiful sky',
       'quick brown fox jumps lazy dog', 'brown fox quick blue dog lazy',
       'sky blue sky beautiful today', 'dog lazy brown fox quick'],
      dtype='<U30')

array(['sky blue beautiful', 'love blue beautiful sky',
       'quick brown fox jumps lazy dog', 'brown fox quick blue dog lazy',
       'sky blue sky beautiful today', 'dog lazy brown fox quick'],
      dtype='<U30')

# Bag of Words Model

array([[1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0],
       [0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0],
       [0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0],
       [1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 1],
       [0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0]], dtype=int64)

C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


beautiful  blue  brown  dog  fox  jumps  lazy  love  quick  sky  today
0          1     1      0    0    0      0     0     0      0    1      0
1          1     1      0    0    0      0     0     1      0    1      0
2          0     0      1    1    1      1     1     0      1    0      0
3          0     1      1    1    1      0     1     0      1    0      0
4          1     1      0    0    0      0     0     0      0    2      1
5          0     0      1    1    1      0     1     0      1    0      0

# Bag of N-Grams Model

C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


(6, 17)

beautiful sky  beautiful today  blue beautiful  blue dog  blue sky  \
0              0                0               1         0         0   
1              1                0               1         0         0   
2              0                0               0         0         0   
3              0                0               0         1         0   
4              0                1               0         0         1   
5              0                0               0         0         0   

   brown fox  dog lazy  fox jumps  fox quick  jumps lazy  lazy brown  \
0          0         0          0          0           0           0   
1          0         0          0          0           0           0   
2          1         0          1          0           1           0   
3          1         1          0          1           0           0   
4          0         0          0          0           0           0   
5          1         1          0          1           0           1   

   lazy dog  love blue  quick blue  quick brown  sky beautiful  sky blue  
0         0          0           0            0              0         1  
1         0          1           0            0              0         0  
2         1          0           0            1              0         0  
3         0          0           1            0              0         0  
4         0          0           0            0              1         1  
5         0          0           0            0              0         0

# TF-IDF Model

C:\Users\Admin\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


beautiful  blue  brown   dog   fox  jumps  lazy  love  quick   sky  today
0       0.60  0.52   0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.60   0.00
1       0.46  0.39   0.00  0.00  0.00   0.00  0.00  0.66   0.00  0.46   0.00
2       0.00  0.00   0.38  0.38  0.38   0.54  0.38  0.00   0.38  0.00   0.00
3       0.00  0.36   0.42  0.42  0.42   0.00  0.42  0.00   0.42  0.00   0.00
4       0.36  0.31   0.00  0.00  0.00   0.00  0.00  0.00   0.00  0.72   0.52
5       0.00  0.00   0.45  0.45  0.45   0.00  0.45  0.00   0.45  0.00   0.00

# Document Similarity

0         1         2         3         4         5
0  1.000000  0.753128  0.000000  0.185447  0.807539  0.000000
1  0.753128  1.000000  0.000000  0.139665  0.608181  0.000000
2  0.000000  0.000000  1.000000  0.784362  0.000000  0.839987
3  0.185447  0.139665  0.784362  1.000000  0.109653  0.933779
4  0.807539  0.608181  0.000000  0.109653  1.000000  0.000000
5  0.000000  0.000000  0.839987  0.933779  0.000000  1.000000

## Clustering documents using similarity features

Document Category  ClusterLabel
0                     The sky is blue and beautiful.  weather             1
1                  Love this blue and beautiful sky!  weather             1
2       The quick brown fox jumps over the lazy dog.  animals             0
3   The brown fox is quick and the blue dog is lazy!  animals             0
4  The sky is very blue and the sky is very beaut...  weather             1
5        The dog is lazy but the brown fox is quick!  animals             0

# Topic models

T1        T2
0  0.190548  0.809452
1  0.176804  0.823196
2  0.846184  0.153816
3  0.814863  0.185137
4  0.180516  0.819484
5  0.839172  0.160828

## Show topics and their weights

[('brown', 1.7273638692668465), ('dog', 1.7273638692668465), ('fox', 1.7273638692668465), ('lazy', 1.7273638692668465), ('quick', 1.7273638692668465), ('jumps', 1.0328325272484777), ('blue', 0.7731573162915626)]

[('sky', 2.264386643135622), ('beautiful', 1.9068269319456903), ('blue', 1.7996282104933266), ('love', 1.148127242397004), ('today', 1.0068251160429935)]



## Clustering documents using topic model features

Document Category  ClusterLabel
0                     The sky is blue and beautiful.  weather             1
1                  Love this blue and beautiful sky!  weather             1
2       The quick brown fox jumps over the lazy dog.  animals             0
3   The brown fox is quick and the blue dog is lazy!  animals             0
4  The sky is very blue and the sky is very beaut...  weather             1
5        The dog is lazy but the brown fox is quick!  animals             0

# Word Embeddings

size: The number of dimensions of the embeddings and the default is 100.

window: The maximum distance between a target word and words around the target word. The default window is 5.

min_count: The minimum count of words to consider when training the model; words with occurrence less than this count will be ignored. The default for min_count is 5.

array([ 0.07380505, -0.01533473, -0.04536615,  0.06554051, -0.0486016 ,
       -0.01816018,  0.0287658 ,  0.00991874, -0.08285215, -0.09448819],
      dtype=float32)

0         1         2         3         4         5         6  \
0  0.041000  0.023496 -0.002957  0.021184 -0.032642 -0.027870  0.055925   
1  0.009201  0.026787  0.010757  0.030243 -0.005814 -0.036322  0.044707   
2 -0.029849  0.023591  0.004554 -0.029321  0.034318 -0.004285 -0.009695   
3 -0.033462  0.023669  0.007271 -0.014668  0.002782 -0.024580  0.015932   
4  0.037648  0.016684 -0.000044  0.039924 -0.040712 -0.016636  0.051486   
5 -0.039082  0.027930 -0.001482 -0.035620  0.021944 -0.015263  0.006201   

          7         8         9  
0  0.030505 -0.053130 -0.073217  
1  0.037997 -0.046948 -0.070347  
2  0.001931 -0.013142  0.030991  
3  0.028622 -0.023004  0.014064  
4  0.010691 -0.054663 -0.049233  
5  0.016401 -0.017574  0.024404

Document Category  ClusterLabel
0                     The sky is blue and beautiful.  weather             0
1                  Love this blue and beautiful sky!  weather             0
2       The quick brown fox jumps over the lazy dog.  animals             1
3   The brown fox is quick and the blue dog is lazy!  animals             1
4  The sky is very blue and the sky is very beaut...  weather             0
5        The dog is lazy but the brown fox is quick!  animals             1